name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      # Only run if gradlew exists
      - name: Check for gradlew
        id: check_gradlew
        run: |
          if [ -f "gradlew" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Build APK (with gradlew)
        if: steps.check_gradlew.outputs.exists == 'true'
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug
      
      - name: Build APK (fallback)
        if: steps.check_gradlew.outputs.exists != 'true'
        run: |
          gradle assembleDebug
      
      - uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
